---
# tasks file for webserver
- name: install httpd software
  package: 
    name: "httpd"
    state: present
 
- name: install php software
  package:
    name: "php"
    state: present

- name: configuring document root directory
  file: 
    state: directory
    dest: "{{ dir }}"
  register: y
  tags: set_dir


- name: copying webpage from any url
  get_url:
          dest: "{{ dir }}"
          url: "https://raw.githubusercontent.com/rahul-yadav-hub/test1/master/testpage.php"
  when: y.failed == false
  tags: deploy

- name: starting service
  service:
          name: "httpd"
          state: started

